name: Build Low End TV APK

on:
  workflow_dispatch:
  push:
    branches:
      - pro-v2

jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Setup Flutter
        uses: subosito/flutter-action@v2
        with:
          flutter-version: '3.22.0'
          channel: stable

      - name: Pub get
        run: flutter pub get

      - name: Build split APK
        run: flutter build apk --release --split-per-abi

      - name: Upload APK
        uses: actions/upload-artifact@v4
        with:
          name: low-end-tv-apk
          path: build/app/outputs/flutter-apk/*.apk
