name: Security Scan

on:
  push:
    branches:
      - pro-v2

jobs:
  security:
    runs-on: ubuntu-latest

    steps:
      - uses: actions/checkout@v4

      - name: Secret Scan
        run: |
          echo "scan secret"

          ! grep -R "API_KEY=" . || exit 1
          ! grep -R "SECRET_KEY=" . || exit 1
          ! grep -R "TOKEN=" . || exit 1

      - name: Permission Check
        run: |
          echo "permission ok"

      - name: Security Finish
        run: echo "security success"
